# Generated by Django 3.2.16 on 2023-08-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('dept', models.CharField(max_length=120)),
                ('roll', models.CharField(max_length=120)),
            ],
        ),
    ]
