# Generated by Django 3.2.16 on 2023-08-02 03:36

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='a/b/c/', validators=[home.models.validate_image])),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
            ],
        ),
    ]
